import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { cookies } from "next/headers";
import { headers } from "next/headers";
import Header from "@/components/header";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["vietnamese"],
  variable: "--font-inter",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore: any = await cookies();
  const sessionToken = cookieStore.get("sessionToken");
  const userId = cookieStore.get("userId");

  return (
    <html lang="vi" suppressHydrationWarning>
      {/* <body
        className={`${inter.variable} antialiased`}
        suppressHydrationWarning
      > <Header/>
      <Sidebar/>
            {children}
      </body> */}
      <body className="min-h-screen bg-gray-50">

        {/* Header trên cùng */}
        <Header />

        {/* Layout dưới: sidebar + content */}
        <div className="flex">

          {/* Sidebar bên trái */}
          <aside className="w-64 h-[calc(100vh-64px)] fixed left-0 top-16 border-r bg-white">
            <Sidebar />
          </aside>

          {/* Content bên phải */}
          <main className="ml-64 mt-5 p-6 w-full">
            {children}
          </main>

        </div>

      </body>
    </html>
  );
}
