import type { Metadata } from "next";
import "./globals.css";
import "./admin.css"
import { Inter } from "next/font/google";
import Link from "next/link";
import { cookies } from "next/headers";
import { headers } from "next/headers";
import Header from "@/components/header";
import Sidebar from "@/components/Sidebar";
import AppProvider from "./AppProvider";

export const metadata: Metadata = {
  title: "Admin Travel",
  icons:{
    icon: "../public/favicon.ico",
  },
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["vietnamese"],
  variable: "--font-inter",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore: any = await cookies();
  const sessionToken = cookieStore.get("sessionToken");
  const userId = cookieStore.get("userId");

  return (
    <html lang="vi" suppressHydrationWarning>
           <AppProvider
            inittialToken={sessionToken?.value}
            inittialUserId={userId?.value}
          >
            <body>
               <main className="w-full">
            {children}
          </main>
            </body>
         
          </AppProvider>
    </html>
  );
}
